comment: false

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: 30...80
  status:
    project:
      default:
        threshold: 10%   # Allows coverage to drop by 10% and still pass
    patch:
      default:
        threshold: 20%   # Allows patch coverage to drop by 20%

ignore:
  - "*/tests/*"                 # Ignore test files in coverage
  - "*/benchmark/*"             # Ignore benchmark files
  - "*/examples/*"              # Ignore example files
  - "setup.py"                  # Ignore setup files
  - "statmoments/_version.py"   # Ignore static version file
